name: NodeJS Express

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
   deployment:
    runs-on: ubuntu-latest
    
    environment: github-pages

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install
      run: npm install
    
    - name: Build
      run: npm run build
    
    - name: Start
      run: npm start
      env:
        JWT_PRIVATE: ${{ secrets.JWT_PRIVATE }}
        DB_CONNECTION_STRING: ${{ secrets.DB_CONNECTION_STRING }}
